export const inputHElement: HTMLInputElement = <HTMLInputElement>document.getElementById('input-h')
export const inputSElement: HTMLInputElement = <HTMLInputElement>document.getElementById('input-s')
export const inputLElement: HTMLInputElement = <HTMLInputElement>document.getElementById('input-l')
export const inputRElement: HTMLInputElement = <HTMLInputElement>document.getElementById('input-r')
export const inputGElement: HTMLInputElement = <HTMLInputElement>document.getElementById('input-g')
export const inputBElement: HTMLInputElement = <HTMLInputElement>document.getElementById('input-b')
export const inputAElement: HTMLInputElement = <HTMLInputElement>document.getElementById('input-a')
export const inputResultElement: HTMLInputElement = <HTMLInputElement>document.getElementById('input-result')

export const hCanvas = <HTMLCanvasElement>document.getElementById('color-h')
export const sCanvas = <HTMLCanvasElement>document.getElementById('color-s')
export const lCanvas = <HTMLCanvasElement>document.getElementById('color-l')
export const rCanvas = <HTMLCanvasElement>document.getElementById('color-r')
export const gCanvas = <HTMLCanvasElement>document.getElementById('color-g')
export const bCanvas = <HTMLCanvasElement>document.getElementById('color-b')
export const aCanvas = <HTMLCanvasElement>document.getElementById('color-a')
export const resultCanvas = <HTMLCanvasElement>document.getElementById('color-result')
export const colorPicker = <HTMLDivElement>document.getElementById('color-picker')

export const layersDiv = <HTMLDivElement>document.getElementById('layers')

export const saveDiv = <HTMLDivElement>document.getElementById('save-div')
export const textureImage = <HTMLImageElement>document.getElementById('texture-image')

export const showCanvas2d = <HTMLCanvasElement>document.getElementById('show-canvas')
export const hotbarCanvas = <HTMLCanvasElement>document.getElementById('hotbar')
export const textureArea = <HTMLImageElement>document.getElementById('texture-area')
export const textureSkinTypeClassic = <HTMLImageElement>document.getElementById('texture-skin-type-classic')
export const textureSkinTypeSlim = <HTMLImageElement>document.getElementById('texture-skin-type-slim')
export const textureChecker = <HTMLImageElement>document.getElementById('texture-checker')

export const skinTypeSelect = <HTMLDivElement>document.getElementById('skin-type-select')
export const skinTypeClassic = <HTMLDivElement>document.getElementById('skin-type-classic')
export const skinTypeSlim = <HTMLDivElement>document.getElementById('skin-type-slim')

export const dragOverlay = <HTMLDivElement>document.getElementById('drag-overlay')

export const addLayerDiv = <HTMLDivElement>document.getElementById('add-layer')
export const removeLayerDiv = <HTMLDivElement>document.getElementById('remove-layer')

export const undoButton = <HTMLDivElement>document.getElementById('top-bar-undo')
export const redoButton = <HTMLDivElement>document.getElementById('top-bar-redo')
export const toggleOuterButton = <HTMLDivElement>document.getElementById('top-bar-toggle-outer')
export const toggleAnimateButton = <HTMLDivElement>document.getElementById('top-bar-toggle-animate')
export const saveButton = <HTMLDivElement>document.getElementById('top-bar-save')

export const toggleHeadButton = <HTMLDivElement>document.getElementById('toggle-part-head')
export const toggleBodyButton = <HTMLDivElement>document.getElementById('toggle-part-body')
export const toggleLeftArmButton = <HTMLDivElement>document.getElementById('toggle-part-left-arm')
export const toggleRightArmButton = <HTMLDivElement>document.getElementById('toggle-part-right-arm')
export const toggleLeftLegButton = <HTMLDivElement>document.getElementById('toggle-part-left-leg')
export const toggleRightLegButton = <HTMLDivElement>document.getElementById('toggle-part-right-leg')
