export const inputHElement: HTMLInputElement = <HTMLInputElement>document.getElementById('input-h')
export const inputSElement: HTMLInputElement = <HTMLInputElement>document.getElementById('input-s')
export const inputLElement: HTMLInputElement = <HTMLInputElement>document.getElementById('input-l')
export const inputRElement: HTMLInputElement = <HTMLInputElement>document.getElementById('input-r')
export const inputGElement: HTMLInputElement = <HTMLInputElement>document.getElementById('input-g')
export const inputBElement: HTMLInputElement = <HTMLInputElement>document.getElementById('input-b')
export const inputAElement: HTMLInputElement = <HTMLInputElement>document.getElementById('input-a')
export const inputResultElement: HTMLInputElement = <HTMLInputElement>document.getElementById('input-result')

export const hCanvas = <HTMLCanvasElement>document.getElementById('color-h')
export const sCanvas = <HTMLCanvasElement>document.getElementById('color-s')
export const lCanvas = <HTMLCanvasElement>document.getElementById('color-l')
export const rCanvas = <HTMLCanvasElement>document.getElementById('color-r')
export const gCanvas = <HTMLCanvasElement>document.getElementById('color-g')
export const bCanvas = <HTMLCanvasElement>document.getElementById('color-b')
export const aCanvas = <HTMLCanvasElement>document.getElementById('color-a')
export const resultCanvas = <HTMLCanvasElement>document.getElementById('color-result')
export const colorPicker = <HTMLDivElement>document.getElementById('color-picker')

export const layersDiv = <HTMLDivElement>document.getElementById('layers')

export const saveDiv = <HTMLDivElement>document.getElementById('save-div')
export const textureCanvas = <HTMLCanvasElement>document.getElementById('texture-canvas')

export const showCanvas2d = <HTMLCanvasElement>document.getElementById('show-canvas')
export const hotbarCanvas = <HTMLCanvasElement>document.getElementById('hotbar')
export const textureArea = <HTMLImageElement>document.getElementById('texture-area')
export const textureChecker = <HTMLImageElement>document.getElementById('texture-checker')

export const skinTypeSelect = <HTMLDivElement>document.getElementById('skin-type-select')
export const skinTypeClassic = <HTMLDivElement>document.getElementById('skin-type-classic')
export const skinTypeSlim = <HTMLDivElement>document.getElementById('skin-type-slim')

export const addLayerDiv = <HTMLDivElement>document.getElementById('add-layer')
export const removeLayerDiv = <HTMLDivElement>document.getElementById('remove-layer')
